username: pradyumna.nunna@gmail.com
password: PradyumnaLi@079
phone_number: +18573967207

profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'


positions:
- Software Engineer
- Software Developer
- Web Developer


locations:
- Boston
- Remote
- United States
- California
- Michigan

salary: 90000
rate: 25
# --------- Optional Parameters -------
uploads:
  Resume: /Users/pradyumna/Documents/Full_Stack_resume_with_3_yrs/Pradyumna_Nunna_Resume.pdf
  #Cover Letter: #
  #Photo: # PATH TO photo


output_filename:
- /Users/pradyumna/Documents/Projects/LinkedIn-Easy-Apply-Bot/out.csv

# blacklist:
# - # Company names you want to ignore

experience_level:
  - 1
  - 2
  - 6