username: 
password: 

positions:
- Data Scientist
- # Another position you want to search for
- # A third position you want to search for

locations:
- Remote
- # A second location you want to search in 

# --------- Optional Parameters -------
# uploads:
#  Resume: # PATH TO Resume 
#  Cover Letter: # PATH TO cover letter
#  Photo: # PATH TO photo


# output_filename:
# - # PATH TO OUTPUT FILE (default output.csv)

# blacklist:
# - # Company names you want to ignore

#blackListTitles:
#- # Add job titles you want to ignore